name: Build and test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release --property OutputPath="./bin"
      - name: Publish Binaries
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/bin/**
            !**/*Tests/bin/**
          if-no-files-found: error
          retention-days: 2
      - name: Publish Test Binaries
        uses: actions/upload-artifact@v4
        with:
          name: build-test-artifacts
          path: |
            **/*Tests/bin/**
          if-no-files-found: error
          retention-days: 1
          
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
      - name: Download build test artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-test-artifacts
          path: ./to-test
      - name: Test
        run: |
          status=0
          shopt -s globstar
          for file in $(ls ./to-test/**/*Tests.dll); do
              echo "Testing $file"
              dotnet test "$file" --verbosity normal --logger trx --filter TestCategory!=FailOnNix --results-directory "./TestResults" || status=1
          done
          exit $status
      - name: Test Report
        uses: bibipkins/dotnet-test-reporter@v1.4.1
        if: success() || failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: 'Unit Test Results'
          results-path: ./TestResults/*.trx