name: Build and test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: './src'
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
      - name: Restore dependencies
        run: dotnet restore ./src
      - name: Build
        run: dotnet build --no-restore --configuration Release --output ./bin
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./bin
          if-no-files-found: error
          retention-days: 1
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release --filter TestCategory!=FailOnNix 